export const TAGS_OF_MARKETS_WITHOUT_DRAW_ODDS = [
  9001, 9002, 9003, 9004, 9005, 9006, 9008, 9007, 9100, 9101, 9153, 9156, 18977,
  18983, 19138, 9020, 9399, 18196, 109021, 9409,
];

export const GOLF_TOURNAMENT_WINNER = [109121];
export const SOCCER = [
  19216, 9042, 9045, 9013, 9015, 9016, 9017, 9018, 9019, 9014, 9057, 9010, 9011,
  9012, 9061, 9076, 9536, 9050,
];

export const LEAGUE_TITLES: Record<string, string> = {
  CsGo: '🔫 CS:GO',
  Boxing: '🥊 Boxing',
  J1: '🇯🇵 Japan J1 ⚽️',
  UFC: '🥊 UFC',
  Dota: '🛡️ Dota',
  MLB: '⚾️ Baseball MLB',
  'Tennis Masters 1000': '🎾 Tennis',
  LOL: '🎮 League of Legends',
  NFL: '🏈 NFL',
  'Champions League Qualification': '⚽ Champions League Qualification',
  'Copa Libertadores': '⚽ Copa Libertadores 🌎',
  'Europa Conference League': '⚽ Europa Conference League',
  'World Cup Woman': '⚽ World Cup Woman 👩',
  EPL: '⚽ English Premier League',
  'La Liga': '⚽ La Liga',
  'France League 1': '⚽ France League 1',
  'Netherlands League 1': '⚽ Netherlands League 1',
  'Portugal League 1': '⚽ Portugal League 1',
  'GOLF Winners': '🏌️‍♂️ GOLF Winners',
  'GOLF H2H': '🏌️‍♂️ GOLF H2H',
  Bundesliga: '🇩🇪 Bundesliga ⚽️',
  MLS: '🇺🇸 MLS ⚽️',
  'Saudi Professional League': '🇸🇦 Saudi Professional League ⚽️',
  'Tennis GS': '🎾 Tennis Grand Slam',
  NCAAF: '🏈 NCAA',
  409: '🏀 Basketball FIBA',
  'EURO Qualification': '⚽ UEFA EURO Qualifiers',
  NBA: '🏀 NBA',
  EuroLeague: '🏀 EUROLEAGUE',
  NHL: '🏒 HOCKEY NHL',
};

export const LEAGUE_KEYS: Record<string, string> = {
  CsGo: 'C',
  Boxing: 'B',
  J1: 'J1',
  UFC: 'U',
  Dota: 'D',
  MLB: 'M',
  'Tennis Masters 1000': 'T',
  LOL: 'LL',
  NFL: 'N',
  'Champions League Qualification': 'CLQ',
  'Copa Libertadores': 'CL',
  'Europa Conference League': 'ECL',
  'World Cup Woman': 'WCW',
  EPL: 'EPL',
  'La Liga': 'LLS',
  'France League 1': 'FL',
  'Netherlands League 1': 'NL',
  'Portugal League 1': 'PL',
  'GOLF Winners': 'GW',
  'GOLF H2H': 'GH',
  Bundesliga: 'BL',
  MLS: 'MLS',
  'Saudi Professional League': 'SPL',
  'Tennis GS': 'TGS',
  NCAAF: 'NCA',
  409: 'BFW',
  'EURO Qualification': 'UEQ',
  NBA: 'NBA',
  EuroLeague: 'EUL',
  NHL: 'NHL',
};
