apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  namespace: sports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot-container
          image: registry.digitalocean.com/sports-app/sports-bot:latest
          imagePullPolicy: Always
      imagePullSecrets:
        - name: my-regcred
